project:
  type: website
  output-dir: docs

permalink: /:title

website:
  title: "Grace M. Horne"
  sidebar:
    pinned: true
    tools:
      - icon: github
        href: https://github.com/gracehorne
        aria-label: GitHub
      - icon: google
        href: https://scholar.google.com/citations?user=pE2oVU0AAAAJ&hl=en
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/ghorneworm
        aria-label: Twitter
      - icon: mastodon
        href: https://mastodon.social/@gracehorne
        aria-label: Mastodon
    style: "floating"
    search: false
    contents:
      - text: "Research"
        href: research.qmd
      - text: "Outreach"
        href: outreach.qmd
      - text: "Resources"
        href: resources.qmd
format:
  html:
    page-layout: full
    anchor-sections: false
    theme: 
      - styles.css
      - simplex
    mainfont: "Avenir Next"
    toc: true 
    backgroundcolor: "#f8f8f2" 
    fontcolor: "#282a36"



